name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nullable/cloudsql-proxy:$GITHUB_SHA
    - name: Push the image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
          name: nullable/cloudsql-proxy:$GITHUB_SHA
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
